### ISSUE TITLE
Bracket matching does not work when in function call

### ISSUE THREAD

**Issue by haze** [flyx/NovaZig#1]
A notable example of this is tuples:

```
std.log.info("test", .
```

typing a `{` here (after the period, for an anonymous tuple) will not insert the corresponding `}`

**Comment by flyx** [comment]
I consulted the docs but there doesn't seem to be a way to configure this.

More thorough checking has shown that this is also an issue with built-in syntaxes. For example, Plain Text and JavaScript do not auto-close

```
.(
.{
-(
-{
```

But HTML does close these:

```
-(
-{
```

So this is indeed influenced by the syntax, but I don't think it's intended. I raised an issue with Panic, let's hear what they say.

**Comment by flyx** [comment]
Panic advised to use an undocumented feature to fix this.

I will try to tackle the other issues as well before releasing a new version.
